Repository Consensys/linea-tracer, pull requests merged in 2024-10, with the labels that each got.

#1336 fix(SELFDESTRUCT): deloyment number
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/TransactionStack.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/types/TransactionProcessingMetadata.java
Labels: bug, reference test

#1337 fix'selfdestruct): immutable map
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/account/AccountFragment.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/AttemptedSelfDestruct.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/EphemeralAccount.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/types/TransactionProcessingMetadata.java
Labels: bug, reference test

#1401 Fixing `underflowException` in `KeccakSection` and same fix for `blockhash` module
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/blockhash/Blockhash.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/KeccakSection.java
Labels: bug

#1410 SELFDESTRUCT static gas in opcodes.yml
  arithmetization/src/main/resources/opcodes.yml
Labels: bug

#1431 `numberOfStackRows()` method to avoid repetition + minor clean up
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/StackOnlySection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TraceSection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCode.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCodeData.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/runtime/stack/Stack.java
Labels: cleaning
