Repository Consensys/linea-tracer, pull requests merged in 2024-12, with the labels that each got.

#1585 clean: no need to store two times same hub in each section
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TraceSection.java
Labels: cleaning

#1640 `HUB -> ROM` lookup fix
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/StackFragment.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCodeData.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCodes.java
Labels: bug, enhancement

#1649 Fixing the 3rd account rows for CREATE's of the FAILURE_WILL_REVERT variety
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/CreateSection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/call/CallSection.java
Labels: bug

#1655 `TX_WARM` fix for addresses which don't exist in the state
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxPreWarmingMacroSection.java
Labels: debugging

#1659 Fix inherited `REVERT_STAMP` of context that `GET_REVERTED` but don't `SELF_REVERT` + some `SSTORE` and `SLOAD` fixes for the `DOM/SUB` stamps
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/SloadSection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/SstoreSection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/runtime/callstack/CallFrame.java
Labels: debugging

#1665 `EXTCODECOPY` requires the `CFI` as its `MMU_SRC_ID` only for addresses not currently under deployment
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/opcode/ExtCodeCopy.java
Labels: bug, debugging
