Repository Consensys/linea-tracer, pull requests merged in 2024-09, with the labels that each got.

#1074 fix(selfdestruct): wrap
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/ReplayTests.java
  arithmetization/src/test/resources/replays/50020-50029.json.gz
Labels: bug

#1070 fix(mmu call): need CFI for failed CREATE2 that doesn't trigger the ROM
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/opcode/Create.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/opcode/Create2.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/opcode/ReturnFromDeployment.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmu/Mmu.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/ReplayTests.java
  arithmetization/src/test/resources/replays/41640-41649.json.gz
Labels: bug

#1081 fix(callDataCopy): source ID
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/MmuCall.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/ReplayTests.java
  arithmetization/src/test/resources/replays/67050-67059.json.gz
Labels: bug

#1094 `TX_SKIP`: canonical snapshots + preconditions
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxSkippedSection.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/module/hub/TxSkipTests.java
Labels: cleaning

#1105 fix(return): OOGX for return for deployment + call SHAKIRA for return…
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/opcode/ReturnFromDeployment.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/CreateSection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/KeccakSection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/call/precompileSubsection/PrecompileSubsection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/call/precompileSubsection/ShaTwoOrRipemdSubSection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/ReturnSection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/shakiradata/HashFunction.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/shakiradata/ShakiraDataOperation.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/ReplayTests.java
  arithmetization/src/test/resources/replays/1002387.json.gz
Labels: bug

#1120 fix CountOnlyModule
  arithmetization/src/main/java/net/consensys/linea/zktracer/container/module/CountingOnlyModule.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/container/stacked/CountOnlyOperation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/Keccak.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/BlakeEffectiveCall.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/BlakeRounds.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/EcAddEffectiveCall.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/EcMulEffectiveCall.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/EcPairingFinalExponentiations.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/EcPairingG2MembershipCalls.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/EcPairingMillerLoops.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/EcRecoverEffectiveCall.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/ModexpEffectiveCall.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/RipemdBlocks.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/Sha256Blocks.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/containers/CountOnlyModuleTest.java
Labels: bug

#1249 perf(WCP): split StackedSet per opcode
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/add/AddOperation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/bin/BinOperation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/euc/EucOperation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/exp/ExpOperation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/ext/ExtOperation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/mod/ModOperation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/mul/MulOperation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/wcp/Wcp.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/wcp/WcpOperation.java
Labels: perf

#1242 Optimize stack related `WCP` operations
  arithmetization/src/main/java/net/consensys/linea/zktracer/container/stacked/NoLineCountStackedSet.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/container/stacked/StackedSet.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/transients/Conflation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/transients/StackHeightCheck.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/runtime/stack/Stack.java
Labels: perf

#1210 add exception if we try to get chainId from a tx wo chainId (v = 27 o…
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/blockdata/Blockdata.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlptxn/RlpTxn.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/types/TransactionUtils.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/BasicAdditionTest.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/StpTests.java
Labels: bug

#1275 New test (that works out of the box) for `ADD`
  arithmetization/src/test/java/net/consensys/linea/replaytests/Issue1274Tests.java
  arithmetization/src/test/resources/replays/7734306.json.gz
Labels: testing

#1310 fix(mmu): invalidCodePrefix with empty memory
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmu/instructions/InvalidCodePrefix.java
Labels: bug, reference test

#1325 refactor: do not postTxDefers TrasactionMetaData
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/types/TransactionProcessingMetadata.java
Labels: cleaning
