Repository Consensys/linea-tracer, pull requests merged in 2025-01, with the labels that each got.

#1698 fix: support default filter for cron job
  .github/workflows/reference-blockchain-tests.yml
Labels: enhancement

#1704 release: bump version to beta-v1.2.0-rc0 and updated CHANGELOG.md
  CHANGELOG.md
  gradle.properties
Labels: release

#1733 clean: remove dead code
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/transients/OperationAncillaries.java
Labels: cleaning

#1747 clean: don't store mmu and mxp stamps with hub and log stamps
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/State.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/TraceSubFragment.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/ImcFragment.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/MxpCall.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/MmuCall.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TraceSection.java
Labels: cleaning

#1729 fix wcp line count for operations coming from block data
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/blockdata/Blockdata.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/blockdata/BlockdataOperation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/blockhash/Blockhash.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/blockhash/BlockhashOperation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/euc/Euc.java
Labels: bug
