Repository Consensys/linea-tracer, pull requests merged in 2025-02, with the labels that each got.

#1734 test: some more skip tests
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxSkipSection.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/module/hub/TxSkipTests.java
Labels: bug, unit tests

#1743 add TX_WARM and TX_FINAL tests
  arithmetization/src/test/java/net/consensys/linea/zktracer/module/hub/TxFinalTest.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/module/hub/TxSkipTests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/module/hub/TxWarmTest.java
Labels: testing, unit tests

#1784 test: mixture of non reverted, self reverted, and get reverted LOGX
  arithmetization/src/test/java/net/consensys/linea/zktracer/module/mmu/RevertingLogsTests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/module/rlptxrcpt/LogTest.java
Labels: testing

#1813 Protect `MODEXP` line counting from integer overflows
  arithmetization/src/main/java/net/consensys/linea/zktracer/container/stacked/CountOnlyOperation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/ModexpEffectiveCall.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/containers/ModexpIllegalOperationTests.java
Labels: bug

#1817 fix: no overflow for BlakeRounds precompile limits count
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/blake2fmodexpdata/BlakeModexpData.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/blake2fmodexpdata/BlakeModexpDataOperation.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/call/precompileSubsection/BlakeSubsection.java
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/BlakeRounds.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/module/precompileLimits/BlakeRoundsTests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/module/precompileLimits/ModexpIllegalOperationTests.java
Labels: bug

#1788 test: add selfdestructing COINBASE
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/selfdestructTests/Heir.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/selfdestructTests/RepeatedSelfDestructsOfSameAccountTests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/selfdestructTests/SelfdestructCoinbaseTests.java
Labels: testing

#1840 release beta-v2.0-rc1: updated `gradle.properties` + `CHANGELOG`
  CHANGELOG.md
  arithmetization/src/main/java/net/consensys/linea/zktracer/module/limits/precompiles/RipemdBlocks.java
  gradle.properties
Labels: release

#1783 Extensive `OOGX` tests involving memory expansion + gas estimation tool `BytecodeRunner.runOnlyForGasCost` + `MSIZE` (#1783)
  arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/ExceptionUtils.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasExceptionTest.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasMemExpExceptionTest.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/module/mmu/MemoryTests.java
  docs/Local-test-coverage.md
  testing/src/main/java/net/consensys/linea/testing/BytecodeRunner.java
  testing/src/main/java/net/consensys/linea/testing/ExecutionEnvironment.java
  testing/src/main/java/net/consensys/linea/testing/GeneralStateReferenceTestTools.java
  testing/src/main/java/net/consensys/linea/testing/ToyExecutionEnvironmentV2.java
Labels: testing

#1837 Generic precompile testing methods
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/CodeExecutionMethods.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecadd/CallParameters.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecadd/HappyPathTests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecadd/MemoryContents.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecadd/ParameterGeneration.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecadd/Tests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecmul/CallDataSizeParameter.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecmul/CallParameters.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecmul/HappyPathTests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecmul/MemoryContents.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecmul/ParameterGeneration.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecmul/Tests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecrecover/CallParameters.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecrecover/EcRecoverTuple.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecrecover/HappyPathTests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecrecover/MemoryContents.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecrecover/ParameterGeneration.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/ecrecover/Tests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/frameWork/PrecompileCallMemoryContents.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/frameWork/PrecompileCallParameters.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/frameWork/PrecompileCallTests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/hash/CallParameters.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/hash/HappyPathTests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/hash/HashPrecompileCallParameters.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/hash/MemoryContents.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/hash/ParameterGeneration.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/hash/Tests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/modexp/ByteSizeParameter.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/modexp/CallDataParameter.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/modexp/CallParameters.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/modexp/HappyPathTests.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/modexp/MemoryContents.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/modexp/ParameterGeneration.java
  arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/callTests/prc/modexp/Tests.java
Labels: testing

#1839 Feat/jacoco reporting on all tests
  .github/workflows/gradle-ethereum-tests.yml
  .github/workflows/gradle-nightly-tests.yml
  .github/workflows/gradle-tests.yml
  .github/workflows/gradle-weekly-tests.yml
  .github/workflows/reference-blockchain-tests.yml
  SETUP.md
  build.gradle
  docs/Local-test-coverage.md
  gradle/tests.gradle
  reference-tests/build.gradle
Labels: enhancement
